version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: notification-service:latest
    container_name: notification-service
    ports:
      - "8084:8084"
    depends_on:
      notification-db:
        condition: service_healthy
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://14.225.212.208:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_IP_ADDRESS=14.225.215.93
      - EUREKA_CLIENT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://notification-db:3306/notification_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8084
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  notification-db:
    image: mysql:8.0
    container_name: notification-db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notification_db
    volumes:
      - notification-mysql-data:/var/lib/mysql
    networks:
      - microservices-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  notification-mysql-data: 