server:
  port: 8087

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:          
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:                   
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: 123456
  mail:
    host: smtp.gmail.com
    port: 587
    username: tbsaptt11@gmail.com
    password: nbdgrilktafkzslx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    defaults:
      enabled: true