version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://14.225.212.208:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_CLOUD_GATEWAY_ROUTES[0].ID=customer-service
      - SPRING_CLOUD_GATEWAY_ROUTES[0].URI=http://14.225.212.208:8081
      - SPRING_CLOUD_GATEWAY_ROUTES[0].PREDICATES[0]=Path=/api/customers/**
      - SPRING_CLOUD_GATEWAY_ROUTES[1].ID=payment-service
      - SPRING_CLOUD_GATEWAY_ROUTES[1].URI=http://14.225.212.208:8085
      - SPRING_CLOUD_GATEWAY_ROUTES[1].PREDICATES[0]=Path=/api/payments/**
      - SPRING_CLOUD_GATEWAY_ROUTES[2].ID=tour-service
      - SPRING_CLOUD_GATEWAY_ROUTES[2].URI=http://14.225.212.208:8083
      - SPRING_CLOUD_GATEWAY_ROUTES[2].PREDICATES[0]=Path=/api/tours/**
      - SPRING_CLOUD_GATEWAY_ROUTES[3].ID=booking-service
      - SPRING_CLOUD_GATEWAY_ROUTES[3].URI=http://14.225.212.208:8082
      - SPRING_CLOUD_GATEWAY_ROUTES[3].PREDICATES[0]=Path=/api/bookings/**
    networks:
      - api-gateway-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure:3

networks:
  api-gateway-network:
    driver: bridge 