server:
  port: 8080

jwt:
  secret: pR8dXJZtG6qM9wKf3uYvL2sBzT4cV1oX5nA7mN0QWgE

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/customer/**

        - id: oauth-service
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/oauth2/**

        - id: tour-service
          uri: lb://TOURSERVICE
          predicates:
            - Path=/tour/**
          filters:
            - AuthenticationFilter  # ✅ Áp dụng filter ở đây

        - id: tour-service
          uri: lb://TOURSERVICE
          predicates:
            - Path=/tours/**
          filters:
            - AuthenticationFilter  # ✅ Áp dụng filter ở đây

        - id: booking-service
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/booking/**
          filters:
            - AuthenticationFilter  # ✅ Áp dụng filter ở đây

        - id: booking-service
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/bookings/**
          filters:
            - AuthenticationFilter  # ✅ Áp dụng filter ở đây

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
