server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/customer/**
        # Route cho /tour
        - id: tour-service-single
          uri: lb://TOURSERVICE
          predicates:
            - Path=/tour/**

        # Route cho /tours
        - id: tour-service-multiple
          uri: lb://TOURSERVICE
          predicates:
            - Path=/tours/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/